import Head from 'next/head'
import { Inter } from 'next/font/google'
import Banner from '../component/home/banner'
import Highlights from '../component/home/highlights'
import Services from '../component/home/services'
import Testimonials from '../component/home/testimonials'
import News from '../component/home/news'
import Footer from '../component/footer'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
  <Banner/>
  <Highlights/>
  <Services/>
  <Testimonials/>
  <News/>
  <Footer/>
    </main>
    </>
  )
}
